### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by natphysnahagey** [launchdarkly/react-native-client-sdk#166]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**

Bare workflow expo app fails to start when the app has been in the background for several hours (eg. overnight).

**To reproduce**
Steps to reproduce the behavior.

1. Start an app with the configuration below (react-native and expo versions listed at the bottom)
2. Close the app for the night
3. Start the app in the morning with `expo start`
4. Open the app on an iPhone (12 Pro iOS version 16.1.1)
5. See console error `Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.`

App.tsx
```
const App = () => {
  const { initializeLdClient } = useLaunchDarkly();

  useEffect(() => {
    initializeLdClient();
  }, []);

  return (<> ...app... < />)
}
```

useLaunchDarkly.ts
``` 
let client: LDClient;

// initialize zustand store with an initializeLdClient method
create<LaunchDarklyState>(set => ({
initializeLdClient: async () => {
    client = new LDClient();
    const config: LDConfig = { mobileKey: MOBILE_KEY };

    // set key from async storage
    // or set to a shared user key (keeping MAUs down to 1)
    const key = (await getItem(LD_STORAGE_KEY)) ?? DEFAULT_LD_USER;

    setItem(LD_STORAGE_KEY, key);

    const user: LDUser = { key };

    try {
      await client.configure(config, user);
    } catch (error) {
      if (error.message === 'LaunchDarkly SDK already initialized') {
        console.warn(error.message);
      } else {
        Track('LD Error', error);
      }
    }

    const isInitialized = await client.isInitialized();
    Track('LD Initialized', { user, isInitialized });

    client.registerAllFlagsListener('id', async () => {
      const allFlags = await client.allFlags();
      set({ allFlags });
    });

    const allFlags = await client.allFlags();
    set({ allFlags });
  }
```

**Expected behavior**

Expecting `NativeEventEmitter` to be called with `LaunchdarklyReactNativeClient`.

**Logs**
If applicable, add any log output related to your problem.

Call stack shows an `error` here:

```
...

  var LaunchdarklyReactNativeClient = _reactNative.NativeModules.LaunchdarklyReactNativeClient;

  var LDClient = function () {
    function LDClient() {
      var _this = this;

      (0, _classCallCheck2.default)(this, LDClient);
<<<<<<< error
      this.eventEmitter = new _reactNative.NativeEventEmitter(LaunchdarklyReactNativeClient);
>>>>>>>
      this.flagListeners = {};
      this.allFlagsListeners = {};
      this.connectionModeListeners = {};

...
```

Previous call:
```
client = new _launchdarklyReactNativeClientSdk.default();
```

Full call stack
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
    at invariant (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:2443:26)
    at NativeEventEmitter (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:34781:32)
    at LDClient (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:211900:62)
    at ?anon_0_ (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:211830:65)
    at next (native)
    at asyncGeneratorStep (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:25356:26)
    at _next (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:25378:29)
    at anonymous (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:25385:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:25374:25)
    at apply (native)
    at initializeLdClient (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:211868:43)
    at anonymous (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:120887:25)
    at commitHookEffectListMount (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:15267:38)
    at commitPassiveMountOnFiber (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:16502:44)
    at commitPassiveMountEffects_complete (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:16467:40)
    at commitPassiveMountEffects_begin (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:16454:47)
    at commitPassiveMountEffects (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:16442:40)
    at flushPassiveEffectsImpl (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:17947:34)
    at flushPassiveEffects (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:17900:43)
    at performSyncWorkOnRoot (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:17285:28)
    at flushSyncCallbacks (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:6974:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:6955:29)
    at scheduleUpdateOnFiber (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:16877:47)
    at updateContainer (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:19392:41)
    at render (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:19992:24)
    at renderApplication (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:110616:78)
    at run (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:110157:28)
    at runApplication (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:110211:28)
    at apply (native)
    at __callFunction (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:24353:36)
    at anonymous (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:24071:31)
    at __guard (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:24297:15)
    at callFunctionReturnFlushedQueue (http://192.168.0.13:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.thangs.mobile:24070:21)
```

**SDK version**
The version of this SDK that you are using.

```
7.2.4
```

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

```
ruby 3.1.2p20
```

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

```
MacOS 12.6 
```

**Additional context**

```
"expo": "^47.0.0",
"react-native": "0.70.5",
```

**Comment by lorenzoangelini** [comment]
Launch darkly seems not work also with react native 71 

NativeModules.LaunchdarklyReactNativeClient is null, could be a linking problem?

**Comment by kevindice** [comment]
This is a problem for me as well.

**Comment by todorone** [comment]
the issue is with `.podspec` file, this patch helped me:

```
diff --git a/node_modules/launchdarkly-react-native-client-sdk/launchdarkly-react-native-client-sdk.podspec b/node_modules/launchdarkly-react-native-client-sdk/launchdarkly-react-native-client-sdk.podspec
index f4cefa4..4c74927 100644
--- a/node_modules/launchdarkly-react-native-client-sdk/launchdarkly-react-native-client-sdk.podspec
+++ b/node_modules/launchdarkly-react-native-client-sdk/launchdarkly-react-native-client-sdk.podspec
@@ -9,7 +9,8 @@ Pod::Spec.new do |s|
   s.homepage     = package["homepage"]
   s.license      = { :type => "Apache-2.0", :file => "LICENSE" }
   s.author       = { "author" => "support@launchdarkly.com" }
-  s.platform     = :ios, "10.0"
+  s.ios.deployment_target = "11.0"
+  s.tvos.deployment_target = "11.0"
   s.source       = { :git => "https://github.com/launchdarkly/react-native-client-sdk.git", :tag => s.version }
   s.source_files  = "ios/**/*.{h,m,swift}"
   s.swift_version = "5.0"
```

**Comment by lorenzoangelini** [comment]
Hi @louis-launchdarkly do you know when launchdarkly will be available with version 0.71?

**Comment by yusinto** [comment]
We are currently working on it and will respond here when we have the release.

**Comment by mikevercoelen** [comment]
@yusinto Bump, we're running into the same problem as well.

**Comment by yusinto** [comment]
We released [7.1.1](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/7.1.1) which contains the patch from @todorone and also supports react-native 0.71.x.

**Comment by mikevercoelen** [comment]
@yusinto It turns out we're using Expo managed workflow and Launch Darkly doesn't support that, which is quite a surprise. 

Expo sucked in the past, but they have improved massively and with the launch of EAS it's now not even worth going bare flow anymore.

More future projects will stay with Expo, for the sake of not having the manage the xcode and android projects manually. 

Do you guys have plan to support it? The only way we can use Launch Darkly right now, is by making our API return feature flags, which is not ideal.

**Comment by todorone** [comment]
@mikevercoelen No need to drop to bare workflow, just use Expo custom dev client to have best of both worlds - any native code including LD + autogenerated iOS/Android native projects by Expo

**Comment by yusinto** [comment]
The react-native SDK have been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. Please consider upgrading to that new version to fix this issue. Thank you for your patience.
