### ISSUE TITLE
How to mock using Jest

### ISSUE THREAD

**Issue by ray-holland-es** [launchdarkly/react-native-client-sdk#202]
**Is your feature request related to a problem? Please describe.**
For web, you have the `jest-launchdarkly-mock` package (that doesn't support react native) where you can mock LD and run you tests.

**Describe the solution you'd like**
I would like it if you make a mock library or prepared documentation on how to get jest tests to work using `react-native-client-sdk`.

Currently, when I run the tests for my application I'm getting the following:

````
 src/App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/my_user/my_project/node_modules/launchdarkly-react-native-client-sdk/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { NativeModules, NativeEventEmitter } from 'react-native';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       7 | import Intercom from "@intercom/intercom-react-native";
    >  8 | import LDClient from "launchdarkly-react-native-client-sdk";
         | ^
       9 | import React, { useEffect, useRef } from "react";

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/App.js:8:1)
      at Object.<anonymous> (src/App.test.js:5:1)

**Comment by louis-launchdarkly** [comment]
Hello @ray-holland-es, thank you for reaching out with the feature request, I have added this to the team's backlog.

Filed Internally as _193002_.

**Comment by ferrannp** [comment]
@ray-holland-es: if you add `launchdarkly-react-native-client-sdk` to `transformIgnorePatterns`, then your unit tests should pass.

**Comment by MDG-MMeksasi** [comment]
@louis-launchdarkly any news with this, or at least any examples on testing in react native

**Comment by ngcvm** [comment]
Hi @louis-launchdarkly, Is there any guide on mocking `@launchdarkly/react-native-client-sdk`?
